baseURL = 'https://davshiv20.github.io/'
languageCode = 'en-us'
title = "Shivam's Blog"
theme = 'PaperMod'
enableRobotsTXT = true
ignoreLogs = ['warning-goldmark-raw-html']

[pagination]
  pagerSize = 5

[params]
  env = "production"
  googleAnalytics = ""  
  mainSections = ["work", "everything", "life", "books"]
  ShowFullTextinRSS = true
  images = ["/images/gohugo-default-sample-hero-image.jpg"]
  
  [params.author]
    name = "Shivam Dave"
    email = "shivam@example.com"
    bio = "Software Engineer passionate about technology and personal growth"

[services]
  [services.rss]
    limit = 20

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

