baseURL = 'https://davshiv20.github.io/'
languageCode = 'en-us'
title = "Shiv's Blog"
theme = 'PaperMod'
enableRobotsTXT = true
ignoreLogs = ['warning-goldmark-raw-html']

[pagination]
  pagerSize = 5

[params]
  env = "production"
  googleAnalytics = ""  

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

